# $FreeBSD$

PORTNAME=	mysql-utilities
PORTVERSION=	1.6.3
CATEGORIES=	databases
MASTER_SITES=	http://dev.mysql.com/get/Downloads/MySQLGUITools/

MAINTAINER=	stdin@niklaas.eu
COMMENT=	Utilities for making common MySQL tasks easy to accomplish

LICENSE=	GPL

NO_ARCH=	yes
USES=		python:2.6-2.7
USE_PYTHON=	distutils autoplist
PYDISTUTILS_INSTALLNOSINGLE=	yes

.include <bsd.port.mk>
