# $FreeBSD$

PORTNAME=	ppl
PORTVERSION=	2.4.0
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	stdin@niklaas.eu
COMMENT=	Command line address book that uses git a vcards for storage

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
